spring.application.name=api-gateway
server.port=8080
eureka.client.serviceUrl.defaultZone=http://user:123456@localhost:8761/eureka/
management.endpoints.web.exposure.include=*

#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true
#logging.level.org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping=DEBUG

# Ignore the compiler error. Eclipse doesn't understand this.
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods= GET, POST, PUT, OPTIONS
## Logging Routes
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator = INFO
logging.level.org.springframework.cloud.gateway = TRACE
## Routes for course service
spring.cloud.gateway.routes[0].id=course-service
spring.cloud.gateway.routes[0].uri=lb://course-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/courses/**
spring.cloud.gateway.routes[0].filters=AuthenticationFilter

## Routes for user service
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[1].filters=AuthenticationFilter

## Routes for user service
spring.cloud.gateway.routes[4].id=order-service
spring.cloud.gateway.routes[4].uri=lb://order-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.routes[4].filters=AuthenticationFilter

## Routes for discovery service
spring.cloud.gateway.routes[2].id=eureka-server
spring.cloud.gateway.routes[2].uri=http://localhost:8761
spring.cloud.gateway.routes[2].predicates[0]=Path=/eureka/web
spring.cloud.gateway.routes[2].filters[0]=SetPath=/

## Routes for discovery service static resource
spring.cloud.gateway.routes[3].id=eureka-server-static
spring.cloud.gateway.routes[3].uri=http://localhost:8761
spring.cloud.gateway.routes[3].predicates[0]=Path=/eureka/**

